# Generated by Django 5.2 on 2025-04-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='Description par défaut'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='Paris', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='Nouvel Hôtel', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='users.hotelowner'),
        ),
    ]
