# Generated by Django 5.2 on 2025-05-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_description_alter_hotel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='last_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='search_vector',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
