# Generated by Django 5.2 on 2025-07-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booking_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(help_text='Number of beds'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Status: Available until booked'),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_booking',
            field=models.DateTimeField(blank=True, help_text='Date of last reservation for this room', null=True),
        ),
    ]
