# Generated by Django 5.2 on 2025-07-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_room_booking_count_remove_room_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True, help_text='Room image URL', max_length=500, null=True),
        ),
    ]
