# Generated by Django 5.2 on 2025-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Room image file', null=True, upload_to='room_images/'),
        ),
    ]
