# Generated by Django 5.2 on 2025-07-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_guests_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
